### ISSUE TITLE
Some modifications

### ISSUE THREAD

**Issue by chdslv** [rauldipeas/Unity-XP#1]
1) If you are using an Ubuntu install to build the iso from the script, you don't need to install `grub-efi-amd64-signed`, as it is already there, but it is needed in the resulting iso, so has to be included in package list.
2) `sh -c "deborphan | xargs sudo apt autoremove --purge -y` is written 3 times, and, it uninstalls compiz-plugins-extra and few packages specifically installed.
3) Maybe, it is better to make the script cleaner, without repeating `sudo chroot $HOME/Unity-XP/chroot` continuously. Maybe, its best to add `sudo chroot $HOME/Unity-XP/chroot /bin/bash` after `sudo mount --bind /run $HOME/Unity-XP/chroot/run` and delete `sudo chroot $HOME/Unity-XP/chroot` from other lines?

**Comment by rauldipeas** [comment]
@chdslv, so many thanks for your feedback and suggestions, this is helping alot!

1. I'll add this package to the script, but alot of users has installed the ISOs that i builded on Azure Pipelines without this package and not occur any kind of problem.

2. This is needed 3 times to remove orphaned packages that when as removed generate another orphaned packages, recursively, i have changed `compiz-plugins-extra`(transition package) to `compiz-plugins`, now it's not removed by `deborphan` command.

3. This script is not interactively, so, you never enter into chroot, the `sudo chroot $HOME/Unity-XP/chroot` is needed to run all commands without enter into it.
