### ISSUE TITLE
Please add /grub/loopback.cfg

### ISSUE THREAD

**Issue by probonopd** [rauldipeas/Unity-XP#6]
Please add `/grub/loopback.cfg` so that we can boot the ISO with GRUB loop-mounting. Thanks.

https://www.supergrubdisk.org/wiki/Loopback.cfg

**Comment by rauldipeas** [comment]
@probonopd @urbancompasspony acho que isso tem relação com aquele rolê que você me pediu do /dev/loop

**Comment by rauldipeas** [comment]
> Please add `/grub/loopback.cfg` so that we can boot the ISO with GRUB loop-mounting. Thanks.
> 
> https://www.supergrubdisk.org/wiki/Loopback.cfg

I'll check this and do it soon!

**Comment by probonopd** [comment]
Thank you very much, it works for me :+1:
