### ISSUE TITLE
Problema na aceleração gráfica em máquina virtual

### ISSUE THREAD

**Issue by leandroungari** [rauldipeas/Unity-XP#9]
Uma dúvida/problema, eu não tenho uma máquina a parte para testar direto as ISOs, então testei usando o VirtualBox. 

Uma coisa que reparei, testando nas suas duas últimas versões lançadas (acho) , se eu criar a máquina e **habilitar a aceleração 3D**, a inicialização acontece normal, inclusive o splash do loading, mas na hora de apresentar a área de trabalho (junto com todos os elementos para interação do usuário) a tela fica inteira preta. 

Se inicializar com a aceleração desabilitada carrega tudo normal, porém com um pouquinho de delay gráfico (suponho eu, se comparado com a aceleração habilitada).

**Comment by rauldipeas** [comment]
Esse é um problema causada por uma incompatibilidade da _GPU_ emulada por padrão no **VirtualBox**, no caso é a **VMSVGA**.

Usando **VBoxSVGA** ou **VBoxVGA**, pode habilitar a aceleração que vai funcionar normalmente.

Outro problema relacionado ao **VirtualBox** é que se você usar apenas um núcleo do seu processador, o sistema também pode não inicializar corretamente, é necessário usar ao menos 2 núcleos.

E pra pontuar tudo que está relacionado à isso, caso você faça a instalação do sistema na máquina virtual, ao rodar as atualizações, novos drivers de vídeo são baixados do repositório **ppa:oibaf/graphics-drivers**, esses drivers também são incompatíveis com o VirtualBox, independente da _GPU_ emulada.

É recomendado desativar esse repositório usando os comandos abaixo:
```
sudo rm -rfv /etc/apt/sources.list.d/*oibaf* /etc/apt/trusted.gpg.d/*oibaf*
sudo apt update
```
